a=int(input("dati a= "))
b=int(input("dati b= "))
c=int(input("dati c= "))
print( a, "+" ,b,"+" ,c, "=",a + b + c)
print(a, "+" ,c, "+" ,b, "=",a + c + b)
print(c, "+" ,b, "+" ,a, "=",c + b + a)
print(c, "+" ,a, "+" ,b, "=",c + a + b)
print(b, "+" ,a, "+" ,c, "=",b + a + c)
